name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  github-release:
    name: GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
