name: Tests

on: [push, pull_request]

jobs:
 test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          curl -OL https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
          sudo apt install ./nvim-linux64.deb

      - name: run tests
        run: nvim --clean --headless --noplugin -u tests/minimal_init.lua -c "PlenaryBustedDirectory tests/ { minimal_init = 'tests/minimal_init.lua' }"
